import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Copy, Plus, RefreshCw, Send, Settings, Trash2, Users } from "lucide-react";
import { useAuth } from "@/contexts/auth";
import { api, type Partner, type PartnerDetail, type PartnerInput } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatTariffOptionLabel } from "@/lib/tariff-label";

const empty: PartnerInput = { name: "", code: "", commissionPct: 20, signupBonus: 100, signupBonusType: "BALANCE", signupTariffId: null, payoutDetails: "", isActive: true };
const rub = (n: number) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 2 }).format(n) + " ₽";

export function PartnersPage() {
  const token = useAuth().state.accessToken!;
  const [partners, setPartners] = useState<Partner[]>([]);
  const [form, setForm] = useState<PartnerInput>(empty);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [detail, setDetail] = useState<PartnerDetail | null>(null);
  const [referralsOpen, setReferralsOpen] = useState(false);
  const [editing, setEditing] = useState<Partner | null>(null);
  const [editForm, setEditForm] = useState<PartnerInput>(empty);
  const [botUsername, setBotUsername] = useState<string | null>(null);
  const [tariffs, setTariffs] = useState<Array<{ id: string; name: string; archivedAt?: string | null }>>([]);
  const load = async () => { setBusy(true); try { const [list, config, tariffList] = await Promise.all([api.getPartners(token), api.getPublicConfig(), api.getTariffs(token)]); setPartners(list.partners); setBotUsername(config.telegramBotUsername?.replace(/^@/, "") ?? null); setTariffs(tariffList.items.map(t => ({ id: t.id, name: t.name, archivedAt: t.archivedAt }))); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось загрузить партнёров"); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [token]);
  const change = (key: keyof PartnerInput, value: string | boolean) => setForm(p => ({ ...p, [key]: ["commissionPct", "signupBonus"].includes(key) ? Number(value) : value }));
  const create = async (e: React.FormEvent) => { e.preventDefault(); setError(""); try { await api.createPartner(token, { ...form, code: form.code.trim().toUpperCase() }); setForm(empty); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось создать партнёра"); } };
  const copy = async (code: string, telegram = false) => { await navigator.clipboard.writeText(telegram && botUsername ? `https://t.me/${botUsername}?start=ref_${encodeURIComponent(code)}` : `${window.location.origin}/cabinet/register?ref=${encodeURIComponent(code)}`); };
  const payout = async (p: Partner) => { if (!p.pending || !confirm(`Отметить выплату ${rub(p.pending)} партнёру ${p.name}?`)) return; await api.payPartner(token, p.id); await load(); };
  const toggle = async (p: Partner) => { await api.updatePartner(token, p.id, { isActive: !p.isActive }); await load(); };
  const open = async (p: Partner) => { setDetail((await api.getPartner(token, p.id)).partner); setReferralsOpen(true); };
  const edit = (p: Partner) => { setEditing(p); setEditForm({ name: p.name, code: p.code, commissionPct: p.commissionPct, signupBonus: p.signupBonus, signupBonusType: p.signupBonusType, signupTariffId: p.signupTariffId, payoutDetails: p.payoutDetails ?? "", isActive: p.isActive }); };
  const remove = async (p: Partner) => { if (!confirm(`Удалить партнёра ${p.name}? История начислений тоже будет удалена.`)) return; await api.deletePartner(token, p.id); await load(); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!editing) return; await api.updatePartner(token, editing.id, { ...editForm, code: editForm.code.trim().toUpperCase() }); setEditing(null); await load(); };
  return <div className="space-y-6 p-4 md:p-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Партнёрская программа</h1><p className="text-sm text-muted-foreground">20% — рабочая стартовая ставка; повышайте для проверенных партнёров.</p></div><Button variant="outline" onClick={load} disabled={busy}><RefreshCw className={busy ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"}/>Обновить</Button></div>
    <form onSubmit={create} className="grid gap-3 rounded-xl border p-4 md:grid-cols-6">
      <div className="md:col-span-2"><Label>Партнёр</Label><Input required value={form.name} onChange={e => change("name", e.target.value)} placeholder="Блогер Иван" /></div>
      <div><Label>Код ссылки</Label><Input required value={form.code} onChange={e => change("code", e.target.value.toUpperCase())} placeholder="IVAN" /></div>
      <div><Label>Комиссия, %</Label><Input required type="number" min="0" max="100" value={form.commissionPct} onChange={e => change("commissionPct", e.target.value)} /></div>
      <div><Label>Бонус</Label><Input required type="number" min="0" value={form.signupBonus} onChange={e => change("signupBonus", e.target.value)} /></div>
      <div><Label>Тип бонуса</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.signupBonusType} onChange={e => setForm(f => ({ ...f, signupBonusType: e.target.value as PartnerInput["signupBonusType"] }))}><option value="BALANCE">На баланс, ₽</option><option value="SUBSCRIPTION">Дней подписки</option></select></div>
      <div><Label>Тариф</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.signupTariffId ?? ""} disabled={form.signupBonusType !== "SUBSCRIPTION"} onChange={e => setForm(f => ({ ...f, signupTariffId: e.target.value || null }))}><option value="">Выберите тариф</option>{tariffs.map(t => <option key={t.id} value={t.id}>{formatTariffOptionLabel(t)}</option>)}</select></div>
      <div className="flex items-end"><Button className="w-full"><Plus className="mr-2 h-4 w-4"/>Создать</Button></div>
      <div className="md:col-span-6"><Label>Реквизиты для выплаты</Label><Input value={form.payoutDetails ?? ""} onChange={e => change("payoutDetails", e.target.value)} placeholder="Банк / СБП / кошелёк — видно только в админке" /></div>
    </form>
    {error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[820px] text-sm"><thead className="bg-muted/50 text-left text-muted-foreground"><tr><th className="p-3">Партнёр и ссылка</th><th className="p-3">Условия</th><th className="p-3">Пришло</th><th className="p-3">К выплате</th><th className="p-3">Выплачено</th><th className="p-3"/></tr></thead><tbody>{partners.map(p => <tr key={p.id} className="border-t"><td className="p-3"><button className="font-medium hover:underline" onClick={() => open(p)}>{p.name}</button><button className="mt-1 flex items-center gap-1 text-xs text-primary hover:underline" onClick={() => copy(p.code)}><Copy className="h-3 w-3"/>Сайт: /cabinet/register?ref={p.code}</button>{botUsername && <button className="mt-1 flex items-center gap-1 text-xs text-primary hover:underline" onClick={() => copy(p.code, true)}><Copy className="h-3 w-3"/>Telegram: t.me/{botUsername}?start=ref_{p.code}</button>}</td><td className="p-3">{p.commissionPct}% с оплат · {p.signupBonus} {p.signupBonusType === "SUBSCRIPTION" ? "дн. подписки" : "₽ на баланс"}</td><td className="p-3"><button className="inline-flex items-center gap-1 hover:underline" onClick={() => open(p)}><Users className="h-4 w-4"/>{p.referrals}</button></td><td className="p-3 font-semibold">{rub(p.pending)}</td><td className="p-3">{rub(p.paid)}</td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={() => edit(p)}><Settings className="mr-1 h-3 w-3"/>Условия</Button><Link to={`/admin/partners/${p.id}/network`}><Button size="sm" variant="outline" className="ml-2">Сеть</Button></Link><Button size="sm" variant="outline" className="ml-2" onClick={() => toggle(p)}>{p.isActive ? "Пауза" : "Включить"}</Button><Button size="sm" variant="outline" className="ml-2" onClick={() => remove(p)}><Trash2 className="mr-1 h-3 w-3"/>Удалить</Button><Button size="sm" className="ml-2" disabled={!p.pending} onClick={() => payout(p)}><Send className="mr-1 h-3 w-3"/>Выплатить</Button></td></tr>)}{!busy && !partners.length && <tr><td colSpan={6} className="p-10 text-center text-muted-foreground">Создайте первого партнёра — его ссылка начнёт учитывать регистрации.</td></tr>}</tbody></table></div>
    <Dialog open={referralsOpen} onOpenChange={setReferralsOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Люди по ссылке {detail?.name}</DialogTitle></DialogHeader><div className="max-h-[60vh] overflow-auto"><table className="w-full text-sm"><tbody>{detail?.referrals.map(r => <tr key={r.id} className="border-t"><td className="p-2">{r.client.telegramUsername ? `@${r.client.telegramUsername}` : r.client.email ?? r.client.id}</td><td className="p-2">{new Date(r.createdAt).toLocaleDateString("ru-RU")}</td><td className="p-2">Оплат: {rub(r.commissions.reduce((s, c) => s + c.amount, 0))}</td><td className="p-2">Бонус: {rub(r.signupBonus)}</td><td className="p-2"><Link className="text-primary hover:underline" to={`/admin/clients?search=${encodeURIComponent(r.client.id)}`} onClick={() => setReferralsOpen(false)}>Открыть клиента</Link></td></tr>)}{!detail?.referrals.length && <tr><td className="p-3 text-muted-foreground">Регистраций пока нет.</td></tr>}</tbody></table></div></DialogContent></Dialog>
    <Dialog open={!!editing} onOpenChange={open => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Условия партнёра</DialogTitle></DialogHeader><form onSubmit={save} className="grid gap-3"><Label>Имя<Input required value={editForm.name} onChange={e => setEditForm(f => ({ ...f, name: e.target.value }))}/></Label><Label>Код ссылки<Input required value={editForm.code} onChange={e => setEditForm(f => ({ ...f, code: e.target.value.toUpperCase() }))}/></Label><div className="grid grid-cols-2 gap-3"><Label>Комиссия, %<Input type="number" min="0" max="100" value={editForm.commissionPct} onChange={e => setEditForm(f => ({ ...f, commissionPct: Number(e.target.value) }))}/></Label><Label>Бонус<Input type="number" min="0" value={editForm.signupBonus} onChange={e => setEditForm(f => ({ ...f, signupBonus: Number(e.target.value) }))}/></Label></div><Label>Тип бонуса<select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={editForm.signupBonusType} onChange={e => setEditForm(f => ({ ...f, signupBonusType: e.target.value as PartnerInput["signupBonusType"] }))}><option value="BALANCE">На баланс, ₽</option><option value="SUBSCRIPTION">Дней подписки</option></select></Label><Label>Тариф<select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={editForm.signupTariffId ?? ""} disabled={editForm.signupBonusType !== "SUBSCRIPTION"} onChange={e => setEditForm(f => ({ ...f, signupTariffId: e.target.value || null }))}><option value="">Выберите тариф</option>{tariffs.map(t => <option key={t.id} value={t.id}>{formatTariffOptionLabel(t)}</option>)}</select></Label><Label>Реквизиты<Input value={editForm.payoutDetails ?? ""} onChange={e => setEditForm(f => ({ ...f, payoutDetails: e.target.value }))}/></Label><Button>Сохранить условия</Button></form></DialogContent></Dialog>
  </div>;
}
